server {
    server_name aslsquads.com www.aslsquads.com;

   location /graphql {
        proxy_pass http://localhost:4000/graphql;
	    proxy_set_header Host $host;
   }

   location /socket.io {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:4000; # Adjust if your app is hosted on a different port
    }


   location /websocket {
        proxy_pass http://localhost:4000/websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

   location / {
       proxy_pass http://localhost:3001/;
       proxy_http_version 1.1;
	   proxy_set_header Host $host;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection 'upgrade';
   }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/aslsquads.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aslsquads.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    server_name admin.aslsquads.com;

    location / {
        proxy_pass http://localhost:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/aslsquads.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aslsquads.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = www.aslsquads.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = aslsquads.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name aslsquads.com www.aslsquads.com;
    return 404; # managed by Certbot




}

server {
    if ($host = admin.aslsquads.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name admin.aslsquads.com;
    return 404; # managed by Certbot


}
