import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ApolloWrapper from '@/lib/ApolloProvider';
import UserProvider, { useUser } from '@/lib/UserProvider';
import Menu from '@/components/layout/Menu';
import Footer from '@/components/layout/Footer';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-950 text-gray-100`}>
        <ApolloWrapper>
          <UserProvider>
            <Menu />
            {children}
            <Footer />
          </UserProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
