name: Deploy Youthspike

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mutation:
    runs-on: ubuntu-latest

    env:
        VPS_USER: ${{ secrets.HOST }}
        VPS_IP: ${{ secrets.USERNAME }}
        VPS_PATH: "/home/shayon/youthspike-event-management"
    steps:       
    - name: Checkout app
      uses: actions/checkout@v4   
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/shayon/youthspike-event-management
          git pull --rebase origin master

  nest_backend:
    needs: [mutation]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: | 
        cd /home/shayon/youthspike-event-management/youthspike-nest-backend
        npm install

    - name: Build and deploy
      run: |
        npm run build
        pm2 startOrRestart ecosystem.config.js --env production
        pm2 save --force

    
