name: Deploy Applications

on:
  push:
    branches: [ master ]

jobs:
  # admin.aslsquads.com
  deploy-admin-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v6


      # 2️⃣ Set up SSH key for VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3️⃣ Copy only the admin frontend project
      - name: Copy admin frontend to VPS
        run: |
          ssh -o StrictHostKeyChecking=no shayon@${{ secrets.YS_ADMIN_FRONTEND_VPS_IP }} "mkdir -p ~/youthspike-admin-frontend"
          rsync -avz --delete \
            --exclude=".env" \
            --filter='P .env' \
            ./youthspike-admin-frontend/ \
            shayon@${{ secrets.YS_ADMIN_FRONTEND_VPS_IP }}:~/youthspike-admin-frontend/



      # 4️⃣ Build and run Docker Compose
      - name: Deploy Docker Compose
        run: |
          ssh shayon@${{ secrets.YS_ADMIN_FRONTEND_VPS_IP }} "cd ~/youthspike-admin-frontend && docker compose pull && docker compose up -d --build"


  # aslsquads.com
    deploy-frontend:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v6

        - name: Test SSH connectivity
          run: |
            nc -zv ${{ secrets.YS_FRONTEND_VPS_IP }} 22 || exit 1

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_FRONTEND_PRIVATE_KEY }}

        - name: Copy frontend to VPS
          run: |
            ssh -o StrictHostKeyChecking=no shayon@${{ secrets.YS_FRONTEND_VPS_IP }} "mkdir -p ~/youthspike-frontend"
            rsync -avz --delete \
              --exclude=".env" \
              --filter='P .env' \
              ./youthspike-frontend/ \
              shayon@${{ secrets.YS_FRONTEND_VPS_IP }}:~/youthspike-frontend/

        - name: Deploy Docker Compose
          run: |
            ssh -o StrictHostKeyChecking=no shayon@${{ secrets.YS_FRONTEND_VPS_IP }} << 'EOF'
              cd ~/youthspike-frontend
              docker compose pull
              docker compose up -d --build --remove-orphans
              docker ps
            EOF
