name: Multi-App CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy-nestjs-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies (Nest.js)
        run: cd youthspike-nest-backend && npm install

      - name: Set Production environment
        run: export NODE_ENV=production

      - name: Build and Test (Nest.js)
        # run: cd youthspike-nest-backend && npm run build && npm test
        run: cd youthspike-nest-backend && npm run build

      - name: Deploy to DigitalOcean (Nest.js)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/shayon/youthspike-event-management
            git pull origin master --rebase
            cd youthspike-nest-backend
            npm install
            npm run build
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save --force

  deploy-nextjs-admin:
    needs: [deploy-nestjs-backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies (Next.js)
        run: cd youthspike-admin-frontend && npm install

      - name: Set Production environment
        run: export NODE_ENV=production

      - name: Build and Test (Next.js)
        # run: cd youthspike-admin-frontend && npm run build && npm test
        run: cd youthspike-admin-frontend && npm run build

      - name: Deploy to DigitalOcean (Next.js)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/shayon/youthspike-event-management/youthspike-admin-frontend
            npm install
            npm run build
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save --force

  deploy-nextjs-frontend:
    needs: [deploy-nestjs-backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies (Next.js)
        run: cd youthspike-frontend && npm install

      - name: Set Production environment
        run: export NODE_ENV=production

      - name: Build and Test (Next.js)
        # run: cd youthspike-frontend && npm run build && npm test
        run: cd youthspike-frontend && npm run build

      - name: Deploy to DigitalOcean (Next.js)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/shayon/youthspike-event-management/youthspike-frontend
            npm install
            npm run build
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save --force
          
          